services:
  mongo:
    image: mongo:4.4
    networks:
      - acheronet
    restart: unless-stopped

  caronte:
    image: ghcr.io/eciavatta/caronte:latest
    ports:
      - "3333:3333"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.caronte.rule=Host(`NETANALYZER_DOMAIN`)"
      - "traefik.http.services.caronte.loadbalancer.server.port=3333"
      - "traefik.http.services.caronte.loadbalancer.server.scheme=http"
      - "traefik.http.routers.caronte.entrypoints=web"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongo
    networks:
      - acheronet
      - proxy-internet
    restart: always

networks:
  acheronet:
  proxy-internet:
    external: true
