services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped

  caronte:
    build: .
    image: caronte:latest
    ports:
      - "3333:3333"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongo
    volumes:
      - ./shared:/opt/caronte/shared
    restart: always
    cpus: 2
    mem_limit: 3g
